### ISSUE TITLE
Compatibilty issue with KSP

### ISSUE THREAD

**Issue by ursusursus** [square/anvil#171] opened 2020-12-22 21:55 UTC
Hi, I'm trying out the experimental ksp because of moshi-ksp; and using Anvil, but after I apply anvil plugin it complains 

```
> Task :app:kspDebugKotlin FAILED
e: Required plugin option not present: com.squareup.anvil.compiler:src-gen-dir

Plugin "com.squareup.anvil.compiler" usage:
  src-gen-dir <file-path>    Path to directory in which Anvil specific code should be generated (required)
  generate-dagger-factories <true|false>
                             Whether Anvil should generate Factory classes that the Dagger annotation processor would generate for @Provides methods and @Inject constructors.


e: Required plugin option not present: com.squareup.anvil.compiler:src-gen-dir
```

I don't even need to have any anvil specific code present, just apply the plugin and it won't compile

Minimal repro: https://github.com/ursusursus/AnvilRepro2/blob/master/app/build.gradle

**Comment by vRallev** [comment] 2020-12-22 22:49
You should file a bug for KSP. The problem is likely that they create a custom Kotlin Compile task for which Anvil registers its compiler plugin. KSP then doesn't forward the compiler plugin flags for Anvil and causes this error.

**Comment by ursusursus** [comment] 2020-12-22 23:16
https://github.com/google/ksp/issues/207

**Comment by ting-yuan** [comment] 2020-12-22 23:52
The compile task created by KSP is front-end only and doesn't perform regular, full analysis. So even if it passes the plugin options of Anvil, it will likely to hit another problem later. In fact, avoiding the interaction with other compiler plugins is one of the reasons that KSP fork its own task to call compiler.

It looks to me that Anvil may also have the same problem with KAPT, which creates two additional compile task: one for stub generation and the other runs annotation processors. How does Anvil work with KAPT?

**Comment by vRallev** [comment] 2020-12-23 01:31
@ting-yuan It's by design that Anvil runs twice for the stub generating task. When KAPT runs, then annotation processors need to see the code that Anvil generated. I assume other compiler plugins will run into a similar problem with KSP plugins and it's not related to Anvil. Until recently before you had the custom task this wasn't an issue. Could your custom task take other compiler plugins into account and not set them up at all?

**Comment by ting-yuan** [comment] 2020-12-23 06:13
@vRallev Compiler plugins are loaded by compiler when they are in compiler's classpath, which is beyond what a subplugin of kotlin-gradle-plugin can control. Fortunately, compiler plugins have a chance in `ComponentRegistrar` to skip registering themselves if they don't see the required options. It is what KAPT's customized tasks do. In this case, you could make `src-gen-dir` optional and only register Anvil when seeing it.

Either plugins that create the task or those that are loaded need to take action to avoid the awkward situation. It seems to me that the former (keeping others from loaded) is much harder, if possible, than the latter (don't load themselves). Anvil is compatible with KAPT because it knows what KAPT does and expected itself to be loaded in KAPT's task. It kind of already took action to accommodate another plugin (KAPT), although in the other way.

**Comment by vRallev** [comment] 2020-12-23 06:24
The things you explain aren't quite right. With the KAPT plugin there are three Gradle tasks in this order: stub generating task, KAPT and the normal Kotlin compile task. Anvil runs for the stub generating and normal compile task, but not the KAPT task. The Kotlin Gradle Plugin adds all compiler plugins to all Kotlin compilation tasks, which the stub generating task extends, but not the KAPT task. 

You create a custom Kotlin compile task. Therefore I assume the Kotlin Gradle Plugin adds all compiler plugins. That's the issue in my opinion. You should only add KSP plugins to your custom compile task. You have control over that, because you create this custom task. 

I cannot make this parameter optional, because it is required. Without the parameter, the plugin would fail. Again, until recently both Anvil and the KSP plugin worked side by side. It broke recently with you introducing the custom task. Like I said, I assume this issue isn't related to Anvil and will happen with other compiler plugins, too.

**Comment by ting-yuan** [comment] 2020-12-23 06:46
Gradle plugins and Kotlin compiler plugins are two different things. Kotlin compiler plugins are loaded whenever they appear in the class path, which is out of my control. I can add new things to it, but knowing what to remove from other plugins or users is practically not possible.

Your compiler plugin won't fail if you don't register it even if it is loaded. In this case, Anvil's Gradle plugin isn't applied at all in KSP's task.

**Comment by ting-yuan** [comment] 2020-12-23 06:56
To be clear, I'm not saying it's Anvil's issue. In my opinion it is an incompatibility of how plugins interact. My point is that it is not possible to fix it cleanly from those who create the tasks, while it should be pretty easy from the other side.

**Comment by vRallev** [comment] 2020-12-23 06:57
Can you remove all compiler plugins from your custom Kotlin task and only add KSP plugins? That should do it, no? Why are plugin options broken with your custom task?

> Your compiler plugin won't fail if you don't register it even if it is loaded. In this case, Anvil's Gradle plugin isn't applied at all in KSP's task.

That scales poorly. Every compiler plugin out there not using KSP would run into the same issue for required plugin options. Suggesting to make them not required isn't great. KSP should not break the API for compiler plugins.

**Comment by ting-yuan** [comment] 2020-12-23 08:00
No. Like I said, it is infeasible to remove compiler plugins or add only what's needed because they are determined by classpath. How do you tell what in compiler's classpath is intended and what is not? It cannot be determined because there are many sources including kotlin-gradle-plugin (and subplugins) and users.

In my opinion, KSP's task behaves exactly the same as KAPT's stub generation task in this case. Anvil happens to work only because it expects KAPT, which doesn't filter out unwanted plugins.

The broken plugin options has nothing to do with this issue.

I agree that making a must-be-defined argument optional sounds bad, but KAPT also behaves in this way. It seems to be an acceptable approach.

On the other hand, when applying the plugin, adding itself to compile classpath means that it will always be loaded in compilation. This is the issue IMHO.

**Comment by vRallev** [comment] 2020-12-24 05:45
> In my opinion, KSP's task behaves exactly the same as KAPT's stub generation task in this case. Anvil happens to work only because it expects KAPT, which doesn't filter out unwanted plugins.

That's not right. Anvil doesn't treat the stub generating task any different when it comes to applying the compiler plugin. https://github.com/square/anvil/blob/main/gradle-plugin/src/main/java/com/squareup/anvil/plugin/AnvilPlugin.kt#L43-L67

> The broken plugin options has nothing to do with this issue.

The issue is that arguments set by the Anvil Gradle plugin for all other Kotlin compile tasks aren't set for the KSP task. That's the exact issue. Your custom KSP task misses a step that normal Kotlin compile task execute. Compiler plugins for your custom task aren't configured. They're applied, but not configured. Same link I posted above. This code should be called for your custom task. 

That's why I suggested to skip any other compiler plugin for your custom KSP task. If not, then you should configure all of them properly like the other Kotlin compile tasks do (including the stub generating task, excluding the KAPT task. The KAPT task itself doesn't run compiler plugins AFAIK). That would be the first step for KSP to be compatible with any compiler plugin.

The 2nd issue is that Anvil doesn't need to run for the KSP task. That's something I need to address. However, KSP should not break other compiler plugins. Unfortunately, that's what is currently happening.

**Comment by vRallev** [comment] 2020-12-28 20:17
@ting-yuan I'm afraid that your suggested workaround won't work. I cannot make the parameter optional like you suggest. Anvil is used with other build tools like Bazel and this could lead to wrong configurations. In fact, KSP configures the custom compile task wrongly and the error is correct. Suggesting to not use an API for compiler plugins is bad, especially since options are required by default: https://github.com/JetBrains/kotlin/blob/29b23e79f32791e456a5b4a453277f0f0b3e984d/compiler/plugin-api/src/org/jetbrains/kotlin/compiler/plugin/CliOptions.kt#L36

This error is unrelated to Anvil. I tried two other compiler plugins with required CLI options and both cause the same failure. The common issue is KSP, not the compiler plugins using an API provided by the compiler.

https://github.com/ZacSweers/redacted-compiler-plugin
```
> Task :app:kspKotlin FAILED
e: Required plugin option not present: redacted-compiler-plugin:enabled

Plugin "redacted-compiler-plugin" usage:
  enabled <true | false>      (required)
  replacementString String    (required)
  redactedAnnotation String   (required)
```

https://github.com/hadilq/trackable-compiler-plugin
```
> Task :app:kspKotlin FAILED
e: Required plugin option not present: trackable-compiler-plugin:enabled

Plugin "trackable-compiler-plugin" usage:
  enabled <true | false>      (required)
  getterName String           (required)
  trackableAnnotation String  (required)
  trackWith String            (required)
``` 
Please reconsider your decision.

**Comment by vRallev** [comment] 2021-01-19 04:37
I'm closing this ticket for now. KSP is breaking Anvil and other compiler plugins. This issue is not related to Anvil.

**Closed by vRallev** 2021-01-19 04:37 UTC
Labels: question, wontfix

**Comment by vRallev** [comment] 2021-01-27 02:02
A workaround has been merged into KSP: https://github.com/google/ksp/pull/270
