### ISSUE TITLE
Let Anvil run when only kaptTest(dagger) is detected

### ISSUE THREAD

**Issue by chrisjenx** [square/anvil#143] opened 2020-10-14 20:29 UTC
Anvil won't run when it detects `@Components`, in most cases we only create `@Component`s in the test classpath.

Wondering if it's possible to support this use case? as would be nice to get the anvil factory generation benefit but still run dagger to generate components for tests?

**Comment by vRallev** [comment] 2020-10-14 22:18
Duplicate of #100

**Closed by vRallev** 2020-10-14 22:18 UTC
