### ISSUE TITLE
Problem with incremental compilation after injection changes in multibindings

### ISSUE THREAD

**Issue by cmorigaki** [square/anvil#705] opened 2023-04-28 14:40 UTC
Problem:
- After changing any of the injected constructor parameters of a class annotated with `@ContributesMultibinding`, the generated map does not include the modified class after and incremental compilation.

Configuration:
- Anvil `2.4.5`
- kotlin `1.8.20`
- multi module project

Steps to reproduce:
1. Download sample [project.zip](https://github.com/square/anvil/files/11354503/multibinds-issue.zip)
2. Run project
3. Check logcat
4. Note that logs will print two entries (as it should)
5. Open LibraryMultibinds.kt
6. Comment out one of the two injected interfaces
7. Run again and check logcat
8. Logs print one entry only, without the modified class

Additional comment:
- This scenario works using Anvil `2.4.4` and kotlin `1.8.0`
- Seems to be similar to https://github.com/square/anvil/issues/693 but different :)

**Comment by ZacSweers** [comment] 2023-05-06 18:27
This is a duplicate of #693, same issue just different manifestation

**Comment by matejdro** [comment] 2023-05-11 08:23
This comment seems to request a new isssue: https://github.com/square/anvil/issues/693#issuecomment-1520317786

**Comment by ZacSweers** [comment] 2023-05-11 13:20
Did you file it on youtrack? This isn't the kotlin issue tracker

**Comment by ZacSweers** [comment] 2023-06-01 03:52
This is a dupe of #693

**Comment by JoelWilcox** [comment] 2023-06-01 20:57
Closing to consolidate with #963

**Closed by JoelWilcox** 2023-06-01 20:57 UTC
