### ISSUE TITLE
Custom compiler extension fails `gradlew clean` on windows

### ISSUE THREAD

**Issue by ursusursus** [square/anvil#458] opened 2021-12-26 01:55 UTC
Hi,
I have a custom anvil compiler extension, and ever since my `gradlew clean` fails with

```
> Task :base:clean FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':base:clean'.
> java.io.IOException: Unable to delete directory 'C:\Users\ursus\AndroidStudioProjects\AnvilCompilerTest\base\build'
    Failed to delete some children. This might happen because a process has files open or has its working directory set in the target directory.
    - C:\Users\ursus\AndroidStudioProjects\AnvilCompilerTest\base\build\libs\base.jar
    - C:\Users\ursus\AndroidStudioProjects\AnvilCompilerTest\base\build\libs
```

Repro is here https://github.com/ursusursus/AnvilCompilerTest

Steps to reproduce
1. gradlew :app:assembleDebug
2. gradlew clean .... observe the mentioned exception

Workaround
1. gradlew --stop
2. gradlew clean ... observe is finishes successfully

**Comment by RBusarow** [comment] 2021-12-26 05:09
I cannot reproduce your issue using that project, but I have a theory based upon similar issues I've had myself.

Your generator has a dependency upon the `:base` module in order to reference its annotation classes.  The generator itself is in the compiler classpath, which means that `:base` module is now in the compiler classpath.  This is different from jvm module dependencies.

The Kotlin compiler has a daemon which lives as long as its host Gradle daemon.  The process is still alive after the build finishes, so it's retaining a reference to that .jar.

These top-level properties:

https://github.com/ursusursus/AnvilCompilerTest/blob/c16962516ac381705021da39dc938999236006f6/custom-annot-compiler/src/main/java/sk/foo/custom_annot/AutoInitializedCodeGenerator.kt#L40-L43

... are _static_ in the JVM, so once they're initialized, they live on until process death.  They might actually be preventing process death?  I'd be interested to see if simply removing those properties would fix your issue.  

If not, it would definitely be fixed by removing the dependency upon `:base`.  Just use a hard-coded string for that FqName.

I don't think that this is technically an Anvil issue.

Also, I don't think it'd make a difference but most of the dependency versions in that repro project are pretty out of date.

**Comment by ursusursus** [comment] 2021-12-26 13:54
@RBusarow I removed both `:base` and `dagger` dependencies from the compiler extension and still no luck

https://github.com/ursusursus/AnvilCompilerTest/blob/master/custom-annot-compiler/src/main/java/sk/foo/custom_annot/AutoInitializedCodeGenerator.kt

any chance this is a windows thing somehow?

**Comment by ursusursus** [comment] 2021-12-26 15:00
I can confirm it works on mac & linux, but fails on windows

**Comment by RBusarow** [comment] 2021-12-26 18:54
I re-installed Parallels just to test this and confirmed that my above suggestions work.

The current state of the project does not cause any errors while cleaning for me (on Windows or macOS).

If I revert your sample project to the state it was in yesterday, I get the same error that you reported above.

Starting from this commit(https://github.com/ursusursus/AnvilCompilerTest/commit/c16962516ac381705021da39dc938999236006f6), I was able to fix the error just by changing those four top-level properties to member properties.  Nothing else.  The generator still has an `implementation` dependency upon `:base`.

After that change, I killed the existing daemon, because it still held the old process with a reference to the .jar.  I then built via `assembleDebug` and was able to `clean` afterwards.

**Comment by ursusursus** [comment] 2021-12-26 19:03
Well, not sure what to do as HEAD doesn't clean successfully for me. Maybe JDK version?

**Comment by RBusarow** [comment] 2021-12-27 00:18
Does HEAD still fail to clean `:base` for you, or has the error switched to the generator module?

> Well, not sure what to do as HEAD doesn't clean successfully for me. Maybe JDK version?

That's possible, I suppose?  I was using the JDK 11 that's bundled with Android Studio.

> How do you kill daemons, `gradlew --stop` ?

Yes, normally.  But that only works for daemons of the same version.  Since you updated Gradle, you may still have (had) a daemon running from the old 7.0.3 version.  

The thorough, nuclear option is to just force quit Java processes from inside task manager.

**Comment by ursusursus** [comment] 2021-12-27 13:59
It's weird. Short of it is nothing works for me to get clean to succeed, unless I gradlew --stop beforehand; then after an assemble, clean always fails

The long of it is, I tried what you said, to reset to the given comit, and just move the static fields to member fields; didn't work, and yes it said lock was on the :base .jar file

Then I reset my self to HEAD, (where the :base dependency was removed completely), and the error message still talk about the :base .jar; 

So I restarted the computer, and now yes the error message talks about the generator module .jar being locked

**Comment by vRallev** [comment] 2021-12-27 17:54
Thanks for the help @RBusarow. Given that this isn't an Anvil issue I'll close this issue.

**Closed by vRallev** 2021-12-27 17:54 UTC
Labels: discussion

**Comment by ursusursus** [comment] 2021-12-27 18:10
Whose issue is it then?

**Comment by vRallev** [comment] 2021-12-27 18:15
Jetbrains in my opinion. Maybe even Gradle.

**Comment by ursusursus** [comment] 2021-12-28 02:23
Are you sure? Anvil, without my extension, works fine, shouldn't it manifest as well if it's kotlin compiler issue?

**Comment by RBusarow** [comment] 2021-12-28 05:26
No, it shouldn't.

With a standard Anvil build, the artifacts come from Maven Central and/or a local Gradle cache.  They're not deleted as part of a clean task.

**Comment by ursusursus** [comment] 2021-12-28 05:36
I see. So you're saying any kotlin compiler plugin built from source will have this issue?
