### ISSUE TITLE
[compiler-api] Compilation Error in generated class when using custom code generator

### ISSUE THREAD

**Issue by MohiteshAeron** [square/anvil#462] opened 2022-01-19 07:22 UTC
I wrote a custom code generator using the `compiler-api` to generate subcomponents for Activities with ContributeSubComponent annotation, but I keep getting the following compilation error

```
e: com.squareup.anvil.compiler.api.AnvilCompilationException: Back-end (JVM) Internal error: Couldn't resolve class for com.sample.anvil.FailingClass_AnvilSubComponent
File is unknown

	at com.squareup.anvil.compiler.internal.PsiUtilsKt.requireClassDescriptor(PsiUtils.kt:765)
	at com.squareup.anvil.compiler.codegen.ContributesSubcomponentHandlerGenerator.findFactoryClass(ContributesSubcomponentHandlerGenerator.kt:387)
	at com.squareup.anvil.compiler.codegen.ContributesSubcomponentHandlerGenerator.generateCode(ContributesSubcomponentHandlerGenerator.kt:206)
	at com.squareup.anvil.compiler.codegen.CodeGenerationExtension.analysisCompleted$generateCode(CodeGenerationExtension.kt:93)
	at com.squareup.anvil.compiler.codegen.CodeGenerationExtension.analysisCompleted(CodeGenerationExtension.kt:107)
```

I noticed that interface is being generated properly with all the annotations and methods in place. Also, if I add the class manually then it works perfectly and compilation doesn't fail. 

I am attaching a sample project with the above use case. Thanks in advance :)
[FailingAnvil.zip](https://github.com/square/anvil/files/7894865/FailingAnvil.zip)

**Comment by vRallev** [comment] 2022-01-20 07:59
Thanks for the sample. Looks like bug to me. I'll take a look.

**Comment by vRallev** [comment] 2022-01-26 18:57
This issue was "accidentally" fixed by this commit: https://github.com/square/anvil/commit/e6d391f7a8c655d2e0ac2903c2f3de661f9f76a2 

I noticed this bug while working on something else and it had the side-effect of fixing this issue, too. The fix will be part of the next release.

**Comment by vRallev** [comment] 2022-01-27 07:49
I need to reopen the issue. While this commit fixes this particular issue, it was wrong and introduced a regression. A proper fix is in the works.

**Closed** 2022-01-27 20:54 UTC
Labels: bug, custom code generator
