### ISSUE TITLE
AssistedInject – BackendException: Backend Internal error: Exception during psi2ir 

### ISSUE THREAD

**Issue by steelahhh** [square/anvil#201] opened 2021-02-13 10:43 UTC
Running into this issue when using `@AssistedInject` on the latest version of Anvil and Kotlin 1.4.30 with `useIR = true`

[Repro repository](https://github.com/steelahhh/anvil-ir-issue)

Steps to reproduce:
- `useIR = true` in build.gradle
- Enable `generateDaggerFactories`
- Create an [@AssistedInject class ](https://dagger.dev/dev-guide/assisted-injection.html)
- Build project - build is successful 
- Change code in any way (see sample in repro repo) and build 
- Following exception is thrown:

```
org.jetbrains.kotlin.backend.common.BackendException: Backend Internal error: Exception during psi2ir
File being compiled: /../../anvil-ir-issue/lib/build/anvil/src-gen-debug/dev/steelahhh/lib/SomeAssistedClass_Factory.kt
The root cause java.lang.NullPointerException was thrown at: kotlin.collections.CollectionsKt___CollectionsKt.joinToString(_Collections.kt)
	at org.jetbrains.kotlin.backend.common.CodegenUtil.reportBackendException(CodegenUtil.kt:239)
	at org.jetbrains.kotlin.backend.common.CodegenUtil.reportBackendException$default(CodegenUtil.kt:235)
	at org.jetbrains.kotlin.psi2ir.generators.DeclarationGenerator.generateMemberDeclaration(DeclarationGenerator.kt:78)
	at org.jetbrains.kotlin.psi2ir.generators.ModuleGenerator.generateSingleFile(ModuleGenerator.kt:83)
	at org.jetbrains.kotlin.psi2ir.generators.ModuleGenerator.generateModuleFragment(ModuleGenerator.kt:50)
	at org.jetbrains.kotlin.psi2ir.Psi2IrTranslator.generateModuleFragment(Psi2IrTranslator.kt:81)
	at org.jetbrains.kotlin.backend.jvm.JvmIrCodegenFactory.generateModule(JvmIrCodegenFactory.kt:106)
	at org.jetbrains.kotlin.codegen.KotlinCodegenFacade.compileCorrectFiles(KotlinCodegenFacade.java:35)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.generate(KotlinToJVMBytecodeCompiler.kt:595)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:211)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:154)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:169)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:52)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:88)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:44)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:98)
	at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:386)
	at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:110)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileIncrementally(IncrementalCompilerRunner.kt:286)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileImpl(IncrementalCompilerRunner.kt:111)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile(IncrementalCompilerRunner.kt:74)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.execIncrementalCompiler(CompileServiceImpl.kt:607)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.access$execIncrementalCompiler(CompileServiceImpl.kt:96)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1659)
	at jdk.internal.reflect.GeneratedMethodAccessor111.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:774)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler$$Lambda$84/0x0000000000000000.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:708)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:836)
Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.collections.CollectionsKt___CollectionsKt.joinToString, parameter $this$joinToString
	at kotlin.collections.CollectionsKt___CollectionsKt.joinToString(_Collections.kt)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinToString$default(_Collections.kt:3340)
	at org.jetbrains.kotlin.ir.util.RenderIrElementVisitor.visitClass(RenderIrElement.kt:459)
	at org.jetbrains.kotlin.ir.util.RenderIrElementVisitor.visitClass(RenderIrElement.kt:30)
	at org.jetbrains.kotlin.ir.declarations.IrClass.accept(IrClass.kt:55)
	at org.jetbrains.kotlin.ir.util.RenderIrElementKt.render(RenderIrElement.kt:28)
	at org.jetbrains.kotlin.ir.symbols.impl.IrBindablePublicSymbolBase.bind(IrPublicSymbolBase.kt:51)
	at org.jetbrains.kotlin.ir.declarations.impl.IrClassImpl.<init>(IrClassImpl.kt:46)
	at org.jetbrains.kotlin.ir.declarations.impl.IrFactoryImpl.createClass(IrFactoryImpl.kt:50)
	at org.jetbrains.kotlin.ir.util.DescriptorToIrUtilKt.createIrClassFromDescriptor(DescriptorToIrUtil.kt:39)
	at org.jetbrains.kotlin.psi2ir.generators.ClassGenerator$generateClass$1.invoke(ClassGenerator.kt:91)
	at org.jetbrains.kotlin.psi2ir.generators.ClassGenerator$generateClass$1.invoke(ClassGenerator.kt:90)
	at org.jetbrains.kotlin.ir.util.SymbolTable.declareClass(SymbolTable.kt:1221)
	at org.jetbrains.kotlin.psi2ir.generators.ClassGenerator.generateClass(ClassGenerator.kt:90)
	at org.jetbrains.kotlin.psi2ir.generators.ClassGenerator.generateClass$default(ClassGenerator.kt:83)
	at org.jetbrains.kotlin.psi2ir.generators.DeclarationGenerator.generateClassOrObjectDeclaration(DeclarationGenerator.kt:104)
	at org.jetbrains.kotlin.psi2ir.generators.DeclarationGenerator.generateMemberDeclaration(DeclarationGenerator.kt:53)
	... 38 more
```

**Comment by vRallev** [comment] 2021-02-13 21:32
I can reproduce the issue. But this seems to be bug in the compiler and I suggest you file a ticket for JetBrains. The problem doesn't happen with the old backend and it doesn't happen when you run another build after a failure. Anvil isn't part of the stacktrace. 

I also tested a JVM module rather than an Android module and can reproduce the problem with your project. 

I suspect it's a problem with incremental compilation and the new IR backend. If I repeat the same steps, but append `-Pkotlin.incremental=false` to the build, then the problem doesn't happen. 

Please link Kotlin ticket in this issue.

**Comment by steelahhh** [comment] 2021-02-14 15:48
Thanks for the info! Filed a ticket: [KT-44925](https://youtrack.jetbrains.com/issue/KT-44925)

**Comment by vRallev** [comment] 2021-02-14 21:31
Thanks! I'll keep this issue open for a while for visibility.

**Comment by sanginovs** [comment] 2021-04-02 16:46
clean build and re-run should resolve this issue

**Comment by vRallev** [comment] 2021-04-13 21:45
I tested `1.5.0-M2` and still was able to reproduce the issue, but not so anymore with `1.5.0-RC` 🎉  Because Anvil is ready for the IR backend and the issue within Kotlin is resolved I'll also close this ticket.

**Closed by vRallev** 2021-04-13 21:45 UTC
Labels: Kotlin IR, wontfix

**Comment by ursusursus** [comment] 2021-04-26 20:02
Doesn't work for me with stable 1.5.0 :/

**Comment by vRallev** [comment] 2021-04-26 20:35
With the sample?

**Comment by ursusursus** [comment] 2021-04-26 20:46
No sorry, I just upgraded kotlin to 1.5.0 and get the same exception. However if I try to get a minimal sample project going, it works, so.. :/

**Comment by ursusursus** [comment] 2021-04-28 00:27
Just a fyi, for me it was this https://youtrack.jetbrains.com/issue/KT-44013

i.e. `object UsageItemMapper : (TotalUsage, List<Service>, UsageDetailTab, Map<String, Product.Options>?, LoadedSubscriber, Boolean) -> List<UsageItem>() {`
        
and this yielded the same stacktrace as OP
It's a kotlin compiler bug, and will be fixed (will throw error since calling super is illegal; i.e. don't call super and your build will pass)

**Comment by vRallev** [comment] 2021-04-28 01:08
Great find, thanks for reporting back.
