### ISSUE TITLE
IDE not syncing on fresh pull

### ISSUE THREAD

**Issue by danielPerez97** [square/anvil#757] opened 2023-10-25 17:47 UTC
I've cloned the repository down and am trying to build and modify the plugin for learning purposes. It get's hung up on this error in IntelliJ Ultimate:

`> Could not get unknown property 'libs' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.`

There appears to be some `includeBuild` magic going on and the `:gradle-plugin` project doesn't end up using the super-projects `libs.versions.toml`.

How can I get this to behave properly? I'd be happy to put this information into a BUILDING.md file or something. Thank you.

Edit: I'm using the following:
IntelliJ IDEA 2023.2.3 Ultimate Edition
Gradle Wrapper
JDK 11.0.20

**Comment by apramana** [comment] 2023-10-25 23:24
This is a dupe of #744. Specifying the version catalog location in the plugin project settings file should fix it, but not sure if there's any consequences to doing so.

**Closed** 2023-11-02 03:15 UTC
