### ISSUE TITLE
Support multiple bound types for contributed bindings and multibindings

### ISSUE THREAD

**Issue by denis-bezrukov** [square/anvil#236] opened 2021-03-23 14:45 UTC
Let's say I have two interfaces `A` and `B` and class implements both:
```
class C @Inject constructor(
   ......
): A, B { 
}
```

to bind it I can add to dagger module:
```
@Binds
@IntoSet
abstract fun bindA(c: C): A

@Binds
@IntoSet
abstract fun bindB(c: C): B
```

As I understand, currently I can bind it only to one of the interfaces via `@ContributesMultibinding` e.g. `@ContributesMultibinding(AppScope::class, A::class)` (and binding to `B` is still in the dagger module). 
Is there a better solution? 

Thanks in advance!

**Comment by vRallev** [comment] 2021-03-23 15:33
No, that's not supported. The recommendation is to create a normal Dagger module and to contribute the module to the same scope. It has the same effect.

**Comment by gpeal** [comment] 2021-03-23 15:41
@vRallev Ah, that's unfortunate. This case may single-handedly prevent us from removing kapt from some modules. Would a reasonable solution be to allow multiple `@ContributesMultibinding` annotations on the same class?

**Comment by vRallev** [comment] 2021-03-23 15:44
No, repeated annotations are only allowed with a source retention. Anvil needs at least class retention.

**Comment by vRallev** [comment] 2021-03-23 15:53
To eliminate Kapt I suggest to use https://github.com/square/anvil#dagger-factory-generation Since Anvil runs in this module anyways the penalty for the module shouldn't be measurable.

**Comment by gpeal** [comment] 2021-03-24 02:08
@vRallev We do use that and you're right about kapt 😄 Thanks for the reply!

**Comment by vRallev** [comment] 2021-03-24 04:32
I don't see it happening without an API breaking change :-) We decided purposefully for one bound type, only.

**Comment by gpeal** [comment] 2021-03-24 15:42
@vRallev just a thought but what if you added `@ContributesMulibinding2` that effectively does the same thing and could be used to add a second :thinking:

**Comment by vRallev** [comment] 2021-03-24 15:52
But what if you need `@ContributesMulibinding3`?

**Comment by gpeal** [comment] 2021-03-24 16:52
@vRallev Of course, there would have to be a cutoff (2, 3, some reasonable value). One way to think of it is a single multibinding probably handles 95% of cases, 2 would get you to 99%, 3 would get you to 99.9% or something like that. 2 or 3 would probably cover the vast majority of the remaining use cases.

That being said, the first one is already a huge win. This is @denis-bezrukov's PR to our codebase :smile: 
![image](https://user-images.githubusercontent.com/1307745/112350563-9946ea80-8c86-11eb-9ff9-d1ea4bf3c0bf.png)

**Comment by denis-bezrukov** [comment] 2021-03-25 08:35
@vRallev @gpeal what if `ContributesMultibinding` will accept optional `val extraBoundTypes: Array<KClass<*> = []` parameter? Then it will work with 2,3,4 types without breaking backward capability
```
@ContributesMultibinding(AppScope::class, A::class, extraBoundTypes = [B::class])
class C @Inject constructor(
   ......
): A, B { 
}
```

**Comment by vRallev** [comment] 2021-03-25 18:40
I thought about that, but it's not great from an API perspective. It will be even more challenging if you want to contribute the different bound types to different scopes.

**Comment by gpeal** [comment] 2021-03-25 23:02
@vRallev While not perfect, I think it is better than having to put one multibinding on the class and one in the a module. While it restricts you one scope, the API at least makes that clear and it would solve most use cases here I think.

**Comment by vRallev** [comment] 2021-03-26 17:15
Let me reopen think about it more. We started rolling out this feature in our codebase last week and have only seen one instance of that so far (well, one instance for multibindings and one instance for normal bindings).

**Comment by vRallev** [comment] 2021-05-29 02:45
I thought about deprecating the `boundType = KClass` attribute in favor of `boundTypes = [KClass]`, but I don't like this approach for two reasons. First, the new attribute would need to be added to the end of the attribute list for source compatibility. The new ordering of the attributes would be strange (right now `boundType` is the 2nd attribute, `boundTypes` would be at the 6th position). Second, the implicit behavior of `ContributesBinding` and `ContributesMultibinding` is that if there's one single super type, then it serves as the default bound type. It's awkward to allow declaring multiple bound types manually, but not respecting multiple super types implicitly. I won't move forward with this option.

The other solution is to allow repeated annotations. However, Kotlin only supports source retention for repeated annotations, but Anvil requires runtime retention to read all annotations from binaries (actually binary retention would be enough, but we decided for source retention to leave the door open for interesting options). So we can't use repeated annotations today. 

Kotlin 1.6 will support repeated annotation with a binary and source retention. The ticket is [KT-12794](https://youtrack.jetbrains.com/issue/KT-12794) and the Keep is available [here](https://github.com/Kotlin/KEEP/blob/repeatable-annotations/proposals/repeatable-annotations.md). For the timeline they mention:
> The prototype is being worked on, and the feature is planned to be included under the -language-version 1.6 flag to Kotlin 1.5.30, and enabled by default since Kotlin 1.6.

That means we could start prototyping this solution relatively soon. My proposal for Anvil would be to make `ContributesTo`, `ContributesBinding` and `ContributesMultibinding` repeatable annotations.

**Comment by BraisGabin** [comment] 2021-10-18 10:38
I would like to share my use case to ilustrate why I would like to have this:

I have a "meta component" of Dagger. It's a component that provides other dagger components. This help me with the modularization and to keep singletons. Because this is a modular project I have interfaces `FeatureAComponentProvider`, `FeatureBComponentProvider` defined in each gradle-module to be able to get the correct component. And then `Application` implements all of them.

So, for that reason my `Application` implements multiple interfaces and I want to bound them all with the `Application` instance. My code looks something like this:

```kotlin
@ContributesBinding(Singleton::class, boundType = Application::class)
class App :
    Application(),
    FeatureAComponentProvider,
    FeatureBComponentProvider,
    FeatureCComponentProvider {

    private val componentFactory: ComponentFactory by lazy {
        DaggerComponentFactory.factory().create(this)
    }

    override fun featureAComponent(): FeatureAComponent {
        return componentFactory.featureAComponent
    }

    override fun featureBComponent(): FeatureBComponent {
        return componentFactory.featureBComponent
    }

    override fun featureCComponent(): FeatureCComponent {
        return componentFactory.featureCComponent
    }
}

@Singleton
@MergeComponent(
    scope = Singleton::class,
)
interface ComponentFactory {
    val featureAComponent: FeatureAComponent
    val featureBComponent: FeatureBComponent
    val featureCComponent: FeatureCComponent

    @Component.Factory
    interface Factory {
        fun create(
            @BindsInstance app: App,
        ): ComponentFactory
    }
}
```

Right now I need to have a `@Binds` for each `ComponentProvider` interface that Application provides. To be honest, it's even worst because I don't want to have all those `@Binds` inside the main gradle-module where `App` is defined (I want to polute the `:app` gradle-module the minimum possible). For that reason I use an `@Provides` in each module with this ugly cast:

```kotlin
@ContributesTo(Singleton::class)
@Module
object FeatureAModule {

  @Provides
  fun componentProvider(application: Application): FeatureAComponentProvider {
    return applcation as FeatureAComponentProvider
  }
}
```

It works but it is ugly and error prone because it can't be catched at compilation time.

For that reason, in my use case, it would be great to generate all the bindings automatically or, at least, be able to define all of them in the annotation so I don't need to write that code.

**Comment by vRallev** [comment] 2021-11-22 01:28
I'd like to give an update for this ticket. I've implemented repeatable annotations for `@ContributesTo` already. It'll be a big change for the Anvil internals, but it's definitely very convenient on the consumers side. 

The problem is that Kotlin 1.6.0 shipped with significant bugs, e.g. incremental compilation [is broken](https://youtrack.jetbrains.com/issue/KT-49822). We'll ship Anvil versions for 1.5 and 1.6 for a longer period of time. But this also means that annotations can't be repeatable, yet.

**Comment by vRallev** [comment] 2021-12-15 04:59
A workaround to start shipping artifacts for Kotlin 1.6 is in #449. In #450 I make `@ContributeTo` repeatable.

**Comment by vRallev** [comment] 2022-03-15 23:58
Closing this issue. Repeatable annotations are part of the next release. If you want, then you can give version `2.4.0-M2` a try. The stable release will be almost identical.

**Closed by vRallev** 2022-03-15 23:58 UTC
Labels: enhancement, discussion
