### ISSUE TITLE
Custom compiler extension not picked up in library module (just app module)

### ISSUE THREAD

**Issue by ursusursus** [square/anvil#369] opened 2021-09-03 02:35 UTC
I'm trying to implement the custom compiler extension.
If I have my custom annotation in :app module then codegen works as expected.
If I have my custom annotation in some :library module, then it is not picked up, even though `anvil project("custom-compiler")`

Here is repro with `anvil` command commented out in :app/build.gradle, 
https://github.com/ursusursus/AnvilCompilerTest

if I comment it back in, you'll notice debugger now hitting break points like so
![image](https://user-images.githubusercontent.com/1503402/131941776-12a9218b-3e82-4a7a-87ed-2989e97a4c20.png)

If you F9 over it, codeGenDir always only talks about  `\app\build...`
If I observe the log from the console after using the `gradlew clean build --no-daemon -Dorg.gradle.debug=true -Dkotlin.compiler.execution.strategy="in-process" -Dkotlin.daemon.jvm.options="-Xdebug,-Xrunjdwp:transport=dt_socket,address=5005,server=y,suspend=n"` command, I notice it executing `:library1:...` without breaking being hit; all pointing to SampleCodeGenerator not being executed in `:library1`

Just to be super sure I throw exception from the SampleCodeGenerator and `anvil project(":custom-annot-processor")` only in `:library1` and clean build completes successfully :/

**Comment by vRallev** [comment] 2021-09-03 03:19
Duplicate of #368

**Closed by vRallev** 2021-09-03 03:19 UTC
